Update homework03.cc
maciekgajewski/c-excercises pull request #111
Opened 2017-02-22 20:15 UTC by AJIEIIIA

implementation

2017-02-23 08:38 UTC, maciekgajewski reviewed
Good

2017-02-23 08:38 UTC, maciekgajewski commented on course5/homework03/homework03.cc
> +    	std::string format = std::string("%.") + std::to_string(precision).c_str() + std::string("f");
Consider ```%.*f```

2017-03-01 21:13 UTC, AJIEIIIA commented
Maciek, why does my program coredump at line 80?

2017-03-01 21:34 UTC, vargad commented on course5/homework04/homework04.cc
> +                Cout = Stream(argv[1]);
Here a temporary Stream object is created, which opens the file named argv[1]. The object get copied to Cout object, effectivly coping the FILE pointer to Cout. After the if statement the temporary Stream object gets destroyed, so it closes the file making the pointer invalid, while the Cout object still has pointer to it.

2017-03-02 08:22 UTC, maciekgajewski requested changes
Please, deliver every homework in a separate pull request

2017-08-28 08:10 UTC, closed without merging