vector homework
maciekgajewski/c-excercises pull request #121
Opened 2017-03-04 15:29 UTC by meszenab

2017-03-05 19:36 UTC, maciekgajewski requested changes
- put main into a separate file
- add unary minus implementation
- expand tests to cover all methods

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +#define Pi 3.14159265
cmath provides the constant

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +int main(int, char**)
As per assignment description: please, put main into a separate file

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.h
> +            Vector2D operator+(const Vector2D&);
Is there a reason why operator+ can't be const?

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.h
> +            Vector2D operator-(const Vector2D&);
Unary minus operator is missing

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.h
> +            bool operator!=(const Vector2D&);
these should be const too

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +        y = src.y;
something's wrong with this line

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +    double Vector2D::GetR() const { return sqrt(x*x + y*y); }
no way this compiles!

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +        Vector2D Y(0, y);
broken intentation

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +    Vector2D operator "" _phi(long double phi) // user can provide phi in degree
Why in degree? All functions in the math lib expect input in radians

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +        if ( x == src.x && y == src.y )
the only purpose of the entire 4-line if statement id to convert bool to bool

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +    double Vector2D::GetR() const { return sqrt(x*x + y*y); }
Please, qualify the library functions: ```std::sqrt```, ```std::sin``` etc

2017-03-05 19:36 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +    std::cout << "v != u: " << (v != u) << std::endl;
Many of the methods remain untested, for instance the getters for radial coords.

2017-03-06 20:17 UTC, meszenab commented on course5/homework5/vector.cc
> +    double Vector2D::GetR() const { return sqrt(x*x + y*y); }
It does compile and gives the expected result. What make you say that? sqrt vs. std::sqrt?

2017-03-06 20:32 UTC, meszenab commented on course5/homework5/vector.h
> +            Vector2D operator+(const Vector2D&);
You mean that the method is const, so
Vector2D operator+(const Vector2D&) const; ?

2017-03-06 21:02 UTC, meszenab commented on course5/homework5/vector.cc
> +        y = src.y;
Hm, seems to work for me. Could you elaborate?

2017-03-07 08:45 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +    double Vector2D::GetR() const { return sqrt(x*x + y*y); }
You must have missed this part of the lecture:
```sqrt``` is a C function that compiles and works here sort of by accident. But C++ only guarantees ```std::sqrt```. There may be a C+ compiler now, or in the future, that will fail to compile the code.

2017-03-07 08:59 UTC, maciekgajewski commented on course5/homework5/vector.cc
> +        y = src.y;
I looked differently when I was looking a it. Maybe github was tricking me...?

2017-03-07 09:00 UTC, maciekgajewski commented on course5/homework5/vector.h
> +            Vector2D operator+(const Vector2D&);
yes

2017-08-28 08:10 UTC, closed without merging