Homework05
maciekgajewski/c-excercises pull request #132
Opened 2017-03-12 19:27 UTC by AJIEIIIA

2017-03-13 09:53 UTC, maciekgajewski requested changes
Mostly good, but tests are only run on a non-const objects, which hides the fact that some of the methods that should be const, aren't.
Try to keep the signal/noise ratio higher.

2017-03-13 09:53 UTC, maciekgajewski commented on course5/homework03/homework03.cc
> -#include <cstdio>
Why does the pull request for homework 5 contain changes to homework 3?

2017-03-13 09:53 UTC, maciekgajewski commented on course5/homework05/.gitignore
> +# This file is used to ignore files which are generated
This is noise; this makes the change more difficult to review.

2017-03-13 09:53 UTC, maciekgajewski commented on course5/homework05/CMakeLists.txt
> +cmake_minimum_required(VERSION 2.8)
Our minimum is 3.0

2017-03-13 09:53 UTC, maciekgajewski commented on course5/homework05/vector2d.h
> +#ifndef VECTOR2D
Use ```#pragma once``` instead.

2017-03-13 09:53 UTC, maciekgajewski commented on course5/homework05/vector2d.h
> +using namespace std::literals;
You are not using any of the literals provided by the standard library, so this is not needed.

2017-03-13 09:53 UTC, maciekgajewski commented on course5/homework05/vector2d.h
> +    Vector2D operator + (const Vector2D& v);
Q: Can this operator modify the LHS object?

2017-03-13 09:53 UTC, maciekgajewski commented on course5/homework05/homework05.cc
> +    auto v1 = Vector2D(1, 0);
Try ``const auto```

2017-04-10 20:53 UTC, AJIEIIIA commented on course5/homework03/homework03.cc
> -#include <cstdio>
removed

2017-04-10 20:54 UTC, AJIEIIIA commented on course5/homework05/vector2d.h
> +#ifndef VECTOR2D
fixed

2017-04-10 20:55 UTC, AJIEIIIA commented on course5/homework05/vector2d.h
> +    Vector2D operator + (const Vector2D& v);
indeed. added const

2017-04-10 20:55 UTC, AJIEIIIA commented on course5/homework05/homework05.cc
> +    auto v1 = Vector2D(1, 0);
added const to methods that do not modify object

2017-04-10 20:58 UTC, AJIEIIIA commented on course5/homework05/vector2d.h
> +using namespace std::literals;
removed

2017-04-10 20:58 UTC, AJIEIIIA commented on course5/homework05/CMakeLists.txt
> +cmake_minimum_required(VERSION 2.8)
fixed

2017-08-28 08:10 UTC, closed without merging