Homework 10-1
maciekgajewski/c-excercises pull request #153
Opened 2017-04-11 19:46 UTC by sophiadavis

Sorry about the diff. Just the last commit has the iterator stuff.

2017-04-12 09:37 UTC, maciekgajewski requested changes
Please, automate your tests, because I don't believe your implementation of end() actually works.

Also - you need a const version of begin and end (+ tests!)

You should also test if you're able to modify the content of your string via iterators.

2017-04-12 09:37 UTC, maciekgajewski commented on course5/homework06/main.cc
> +    std::cout << any_a << std::endl;
Please ,automate the tests

2017-04-12 09:37 UTC, maciekgajewski commented on course5/homework06/simple_string.h
> +    iterator begin() { return &buffer.get()[0]; }
Knowing that for any pointer ```p``` and integer ```i```, the following expression are identical:
```p[i]``` === ```*(p + i)```
and
```&(*p)``` === ```p```
And knowing that ```buffer.get()``` is a pointer

How can you simplify this function?

2017-04-12 09:37 UTC, maciekgajewski commented on course5/homework06/simple_string.h
> +    iterator end() { return &buffer.get()[l]; }
I don't think this would work

2017-04-12 19:35 UTC, sophiadavis commented on course5/homework06/simple_string.h
> +    iterator end() { return &buffer.get()[l]; }
It seems to be working...? What am I doing wrong?

2017-04-13 09:05 UTC, maciekgajewski reviewed
Of course it's good; I was confused by combination of bad typeface and your minimalistic variable names.

2017-04-13 09:05 UTC, maciekgajewski commented on course5/homework06/simple_string.h
> +    iterator end() { return buffer.get() + l; }
OK. it is l (small-caps L), not 1 (one). So confusing...
See, ```mLength``` or ```length_``` or ```this->l``` would be much easier to read.

Of course it's good.

2017-04-13 09:05 UTC, maciekgajewski commented on course5/homework06/simple_string.h
> +    iterator begin() { return buffer.get(); }
You also need const begin and end, otherwise you wouldn't be able to iterate over const object.

2017-08-28 08:09 UTC, closed without merging