Sqrt newton
maciekgajewski/c-excercises pull request #94
Opened 2017-02-11 15:43 UTC by meszenab

Newton's method for sqrt

2017-02-13 09:11 UTC, maciekgajewski reviewed
Try without using global variables.
Also, I don't think the number of iterations should be part of the interface.

2017-02-13 09:11 UTC, maciekgajewski commented on course5/homework2/newton/newton.cc
> +int i = 0;
Didn't I explicitly asked in the alignements not to use global variables?
Maybe I forgot...
Anyway, try again, without global variables!

2017-02-13 09:11 UTC, maciekgajewski commented on course5/homework2/newton/newton.cc
> +    std::cout << "calculation time: " << t << std::endl;
It isn't calculation time; it's "calculation and printing time"

2017-02-13 09:11 UTC, maciekgajewski commented on course5/homework2/newton/newton.cc
> +    int size = (start - end)/i;
So, any conclusions? Hoe big is the stack frame? What is the impact of the build type on the stack frame size?

2017-02-13 09:12 UTC, maciekgajewski requested changes
Try without using global variables.
Also, I don't think the number of iterations should be part of the interface.

2017-02-13 20:12 UTC, meszenab commented on course5/homework2/newton/newton.cc
> +    int size = (start - end)/i;
The stack frame was 48 for debug mode and bigger (64) in release mode

2017-02-14 08:16 UTC, maciekgajewski requested changes
You still have global variables in there

2017-02-14 08:16 UTC, maciekgajewski commented on course5/homework2/newton/newton.cc
> +bool* start = nullptr;
These are still global. And you don't need bool. To store pure, untyped address just use void*

2017-02-14 08:16 UTC, maciekgajewski commented on course5/homework2/newton/newton.cc
> +float function( float y, int it, float& rx, int& ri)
"function" is not the best name for a function calculating square root. Make your API such so you'd enjoy using it.

2017-02-14 08:16 UTC, maciekgajewski commented on course5/homework2/newton/newton.cc
> +    float& rx = x;
you don't need these

2017-08-28 08:10 UTC, closed without merging